apiVersion: v1
kind: Service
metadata:
  name: account-service
spec:
  selector:
    deploymentconfig: account-service     
  ports:
  - nodePort: 0
    port: 8095              
    protocol: TCP
    targetPort: 8095