apiVersion: v1
kind: Service
metadata:
  name: customer-service
spec:
  selector:
    deploymentconfig: customer-service     
  ports:
  - nodePort: 0
    port: 8080              
    protocol: TCP
    targetPort: 8090